"""CheckList and List Item tables added

Revision ID: a23aef9ccda5
Revises: 58e9c34402c9
Create Date: 2020-05-23 12:34:56.951497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23aef9ccda5'
down_revision = '58e9c34402c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_list_creation_date'), 'check_list', ['creation_date'], unique=False)
    op.create_index(op.f('ix_check_list_title'), 'check_list', ['title'], unique=True)
    op.create_table('list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['check_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_item_creation_date'), 'list_item', ['creation_date'], unique=False)
    op.create_index(op.f('ix_list_item_title'), 'list_item', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_item_title'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_creation_date'), table_name='list_item')
    op.drop_table('list_item')
    op.drop_index(op.f('ix_check_list_title'), table_name='check_list')
    op.drop_index(op.f('ix_check_list_creation_date'), table_name='check_list')
    op.drop_table('check_list')
    # ### end Alembic commands ###
