"""ListItem Table

Revision ID: b634fc11dba1
Revises: dc95d6143339
Create Date: 2020-05-23 10:40:02.543097

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b634fc11dba1'
down_revision = 'dc95d6143339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('checklist_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['checklist_id'], ['check_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_item_creation_date'), 'list_item', ['creation_date'], unique=False)
    op.create_index(op.f('ix_list_item_title'), 'list_item', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_item_title'), table_name='list_item')
    op.drop_index(op.f('ix_list_item_creation_date'), table_name='list_item')
    op.drop_table('list_item')
    # ### end Alembic commands ###
