"""CheckList table

Revision ID: dc95d6143339
Revises: 58e9c34402c9
Create Date: 2020-05-23 10:09:39.250381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc95d6143339'
down_revision = '58e9c34402c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('check_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_list_creation_date'), 'check_list', ['creation_date'], unique=False)
    op.create_index(op.f('ix_check_list_title'), 'check_list', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_check_list_title'), table_name='check_list')
    op.drop_index(op.f('ix_check_list_creation_date'), table_name='check_list')
    op.drop_table('check_list')
    # ### end Alembic commands ###
